server:
  port: 8086

security:
  jwt:
    secret_key: cubs3d-jwt-@SeCr3tK3y
    expiration_ms: 86400000

spring:
  application:
    name: account
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/account
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka
      fetch-registry: true
      register-with-eureka: true
