server:
  port: 8086

spring:
  appplication:
    name: item-editor
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/item-editor
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true