server:
  port: 8091

spring:
  application:
    name: moderation

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/moderation

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        healthCheckCriticalTimeout: 45s
        queryPassing: true
    loadbalancer:
      ribbon.enabled: false
