server:
  port: 8091

spring:
  application:
    name: moderation
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/moderation
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka
      fetch-registry: true
      register-with-eureka: true
