server:
  port: 8080

websocket:
  handler:
    path: /nhg/game

commands:
  prefixes: >
    :,
    /

spring:
  application:
    name: game

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://game-service-db:5432/db
    initialization: ALWAYS

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        lob:
          non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
      host: http://localhost
      port: 6379
      database: 1

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        healthCheckCriticalTimeout: 45s
        queryPassing: true
    loadbalancer:
      ribbon.enabled: false

logging:
  level:
    com:
      nhg:
        game: DEBUG
    org:
      springframework:
        web:
          client:
            RestTemplate: ERROR